// 影院域原型演示数据（prototype.html 专用，不进构建）。
// 由真实 vault 笔记导出（671 部取有海报的 50 部，2026-09-07），
// 海报为 vault 绝对 file:// 路径，双击原型即可加载真图。
window.CINEMA_DATA = [
  {
    "name": "完美的日子",
    "typeTag": "电影",
    "group": "电影",
    "status": "已看",
    "rating": 9.9,
    "watchDate": "2024-04-08",
    "review": "影像的张力，内心的艺术，原来这就是热爱生活啊！平山口袋里的奥林巴斯给了骑行一个答案，不是我没勇气，是不够向往。之后，我也去拍了许多树。有时，我觉得自己也像一棵树，扎根在自己的身体里，静静看着世界流转。春去秋来，阴晴圆缺。",
    "poster": "file:///E:/Obsidian/%E5%8F%AB%E6%88%91%E5%8C%85%E4%BB%94/CONFIG/MOVIE%20POSTER/Pasted%20image%2020240408004831.png",
    "genre": "剧情",
    "director": "维姆·文德斯",
    "actors": "役所广司",
    "region": "日本 / 德国",
    "year": "2023",
    "doubanRating": "8.5",
    "doubanUrl": "https://movie.douban.com/subject/35902857/",
    "synopsis": "讲述一名东京公共洗手间清洁工大叔的文艺生活。看树木和光影，听磁带，读书，拍胶片，在平凡日常中寻找美好。"
  },
  {
    "name": "少年派的奇幻漂流",
    "typeTag": "电影",
    "group": "电影",
    "status": "已看",
    "rating": 9.8,
    "watchDate": "2017-01-17",
    "review": null,
    "poster": "file:///E:/Obsidian/%E5%8F%AB%E6%88%91%E5%8C%85%E4%BB%94/CONFIG/MOVIE%20POSTER/Pasted%20image%2020260501225803.png",
    "genre": "剧情 / 奇幻 / 冒险",
    "director": "李安",
    "actors": "苏拉·沙玛 / 伊尔凡·可汗 / 拉菲·斯波 / 阿迪勒·侯赛因 / 塔布",
    "region": "美国",
    "year": "2012",
    "doubanRating": "9.1",
    "doubanUrl": "https://movie.douban.com/subject/1929463/",
    "synopsis": "影片讲述少年派遇到一次海难，家人全部丧生，他与一只孟加拉虎在救生小船上漂流了227天，人与虎建立起一种奇特的关系，并共同面对困境获得重生。"
  },
  {
    "name": "地球脉动 第一季",
    "typeTag": "纪录片",
    "group": "纪录片",
    "status": "已看",
    "rating": 9.8,
    "watchDate": "2017-02-27",
    "review": null,
    "poster": "file:///E:/Obsidian/%E5%8F%AB%E6%88%91%E5%8C%85%E4%BB%94/CONFIG/MOVIE%20POSTER/1214927835.jpg",
    "genre": "纪录片",
    "director": "艾雷斯泰·法瑟吉尔 / 马克·林菲尔德",
    "actors": "大卫·爱登堡 / 西格妮·韦弗",
    "region": "英国",
    "year": "2006",
    "doubanRating": "9.7",
    "doubanUrl": "https://movie.douban.com/subject/1871906/",
    "synopsis": "BBC曾制作《蓝色星球》的纪录片摄影团队再次集结，奉上这部堪称难以超越的经典。从南极到北极，从赤道到寒带，从非洲草原到热带雨林，再到荒凉峰顶与深邃大海，无数生物以绝美身姿呈现在世人面前。片中可见奥卡万戈洪水的涨落、罕见雪豹在漫天大雪中猎食的珍贵画面、冰原上企鹅与北极熊的生存情景，以及大洋深处火山口高温环境下的惊奇生物。拍摄期间还采用了美国军方发明的空中摄影机，可从一公里外拍摄超清晰特写。"
  },
  {
    "name": "地球脉动 第二季",
    "typeTag": "纪录片",
    "group": "纪录片",
    "status": "已看",
    "rating": 9.8,
    "watchDate": "2017-03-08",
    "review": null,
    "poster": "file:///E:/Obsidian/%E5%8F%AB%E6%88%91%E5%8C%85%E4%BB%94/CONFIG/MOVIE%20POSTER/1215062315.jpg",
    "genre": "纪录片",
    "director": "伊丽莎白·怀特 / 贾斯汀·安德森 / 艾玛·纳珀 / 艾德·查尔斯 / 查登·亨特 / 弗雷迪·德瓦斯",
    "actors": "大卫·爱登堡",
    "region": "英国",
    "year": "2016",
    "doubanRating": "9.9",
    "doubanUrl": "https://movie.douban.com/subject/27087625/",
    "synopsis": "《地球脉动2》是BBC经典自然纪录片《地球脉动》（2006）时隔十年的回归之作。全片共6集，分别以岛屿、山脉、丛林、沙漠、草原、城市六种截然不同的栖息地为主题，带领观众近距离见证地球各个角落动物与植物的生存故事——树懒、巨蜥、狐猴、海鬣蜥、帽带企鹅、雪豹、金雕、蜘蛛猴、美洲豹等万千生物在严苛自然环境中的顽强挣扎与生命光辉。该片采用超高清4K摄影机拍摄，并运用无人机和远程控制拍摄技术，历时三年、走遍40个国家。"
  },
  {
    "name": "肖申克的救赎",
    "typeTag": "电影",
    "group": "电影",
    "status": "已看",
    "rating": 9.8,
    "watchDate": "2021-12-09",
    "review": null,
    "poster": "file:///E:/Obsidian/%E5%8F%AB%E6%88%91%E5%8C%85%E4%BB%94/CONFIG/MOVIE%20POSTER/Pasted%20image%2020260501210400.png",
    "genre": "剧情 / 犯罪",
    "director": "弗兰克·德拉邦特",
    "actors": "蒂姆·罗宾斯 / 摩根·弗里曼 / 鲍勃·冈顿 / 威廉姆·赛德勒 / 克兰西·布朗",
    "region": "美国",
    "year": "1994",
    "doubanRating": "9.7",
    "doubanUrl": "https://movie.douban.com/subject/1292052/",
    "synopsis": "20世纪40年代末，银行家安迪因涉嫌杀害妻子及其情人被误判入狱，判处终身监禁。在肖申克监狱中，他结识了狱中颇有声望的瑞德，利用自己的专业知识帮监狱管理层逃税洗钱，并凭借对自由的渴望，在漫长的岁月中谋划了一场惊心动魄的越狱。该片改编自斯蒂芬·金的小说，多年来稳居豆瓣和IMDb评分榜首，被誉为影史经典。"
  },
  {
    "name": "绿色星球",
    "typeTag": "纪录片",
    "group": "纪录片",
    "status": "已看",
    "rating": 9.8,
    "watchDate": "2022-03-09",
    "review": null,
    "poster": "file:///E:/Obsidian/%E5%8F%AB%E6%88%91%E5%8C%85%E4%BB%94/CONFIG/MOVIE%20POSTER/1215304318.jpg",
    "genre": "纪录片",
    "director": "西蒙·拜福德",
    "actors": "大卫·爱登堡",
    "region": "英国",
    "year": "2022",
    "doubanRating": "9.6",
    "doubanUrl": "https://movie.douban.com/subject/35411179/",
    "synopsis": "BBC自然纪录片，运用革命性延时摄影技术，揭示植物世界里不为人知的生存策略与惊人智慧。"
  },
  {
    "name": "卡尔·萨根的宇宙",
    "typeTag": "纪录片",
    "group": "纪录片",
    "status": "已看",
    "rating": 9.8,
    "watchDate": "2024-03-03",
    "review": null,
    "poster": "file:///E:/Obsidian/%E5%8F%AB%E6%88%91%E5%8C%85%E4%BB%94/CONFIG/MOVIE%20POSTER/1215811535.jpg",
    "genre": "纪录片",
    "director": "阿德里安·马隆 / David F. Oyster",
    "actors": "卡尔·萨根",
    "region": "美国",
    "year": "1980",
    "doubanRating": "9.4",
    "doubanUrl": "https://movie.douban.com/subject/1422169/",
    "synopsis": "卡尔·萨根对科学和社会的诸多方面都有重大深远的贡献，并且影响了全世界数以亿计的人们。本片是科学纪录片的经典之作，由著名天文学家、科普作家卡尔·萨根亲自制作并主讲。节目通过\"想象之舟\"带领观众穿越时空，涵盖天文学历史、宇宙学、生命起源、恒星演化、外星生命探索等广泛主题。该片播出后在全球60多个国家播放，吸引了多达5亿观众，并获得艾美奖和皮博迪奖。"
  },
  {
    "name": "阿甘正传",
    "typeTag": "电影",
    "group": "电影",
    "status": "已看",
    "rating": 9.8,
    "watchDate": "2024-06-30",
    "review": "励志向上之后的一片静默。",
    "poster": "file:///E:/Obsidian/%E5%8F%AB%E6%88%91%E5%8C%85%E4%BB%94/CONFIG/MOVIE%20POSTER/Pasted%20image%2020260508181511.png",
    "genre": "剧情 / 爱情",
    "director": "罗伯特·泽米吉斯",
    "actors": "汤姆·汉克斯 / 罗宾·怀特 / 加里·西尼斯 / 莎莉·菲尔德 / 麦凯尔泰·威廉逊",
    "region": "美国",
    "year": "1994",
    "doubanRating": "9.5",
    "doubanUrl": "https://movie.douban.com/subject/1292720/",
    "synopsis": "智商只有75的阿甘却有着惊人的运动天赋，他见证了肯尼迪遇刺、越战、水门事件等重大历史时刻，用奔跑诠释了“人生就像一盒巧克力”的哲理。"
  },
  {
    "name": "太阳系",
    "typeTag": "纪录片",
    "group": "纪录片",
    "status": "已看",
    "rating": 9.8,
    "watchDate": "2024-10-28",
    "review": null,
    "poster": "file:///E:/Obsidian/%E5%8F%AB%E6%88%91%E5%8C%85%E4%BB%94/CONFIG/MOVIE%20POSTER/1215653128.jpg",
    "genre": "纪录片",
    "director": "弗勒·伯恩",
    "actors": "布莱恩·考克斯",
    "region": "英国",
    "year": "2025",
    "doubanRating": "9.2",
    "doubanUrl": "https://movie.douban.com/subject/37079530/",
    "synopsis": "Professor Brian Cox reveals the strange worlds of the solar system, visible to us as never before seen."
  },
  {
    "name": "行星",
    "typeTag": "纪录片",
    "group": "纪录片",
    "status": "已看",
    "rating": 9.8,
    "watchDate": "2025-01-23",
    "review": null,
    "poster": "file:///E:/Obsidian/%E5%8F%AB%E6%88%91%E5%8C%85%E4%BB%94/CONFIG/MOVIE%20POSTER/1215698860.jpg",
    "genre": "纪录片",
    "director": "斯蒂芬·库特",
    "actors": "布莱恩·考克斯",
    "region": "英国",
    "year": "2019",
    "doubanRating": "9.6",
    "doubanUrl": "https://movie.douban.com/subject/30466564/",
    "synopsis": "BBC宇宙纪录片，布莱恩·考克斯教授带领观众探索太阳系各大行星的奥秘，以史诗级视觉呈现宇宙之美。"
  },
  {
    "name": "宇宙",
    "typeTag": "纪录片",
    "group": "纪录片",
    "status": "已看",
    "rating": 9.8,
    "watchDate": "2025-01-24",
    "review": null,
    "poster": "file:///E:/Obsidian/%E5%8F%AB%E6%88%91%E5%8C%85%E4%BB%94/CONFIG/MOVIE%20POSTER/1215752071.jpg",
    "genre": "纪录片",
    "director": null,
    "actors": null,
    "region": "美国",
    "year": "2008",
    "doubanRating": "9.3",
    "doubanUrl": "https://movie.douban.com/subject/4023348/",
    "synopsis": "由History Channel制作的宇宙科普纪录片，带领观众探索太阳系、银河系乃至整个宇宙的奥秘。"
  },
  {
    "name": "横道世之介",
    "typeTag": "电影",
    "group": "电影",
    "status": "已看",
    "rating": 9.8,
    "watchDate": "2026-04-02",
    "review": "这人间本不该让我如此欣喜，但是，你来了。",
    "poster": "file:///E:/Obsidian/%E5%8F%AB%E6%88%91%E5%8C%85%E4%BB%94/CONFIG/MOVIE%20POSTER/55847364.jpg",
    "genre": "剧情 / 爱情 / 家庭",
    "director": "冲田修一",
    "actors": "高良健吾 / 吉高由里子 / 池松壮亮 / 伊藤步 / 绫野刚",
    "region": "日本",
    "year": "2013",
    "doubanRating": "8.8",
    "doubanUrl": "https://movie.douban.com/subject/10755372/",
    "synopsis": "横道世之介是一个来自长崎的普通大学生，性格单纯善良，他在东京的校园生活中结识了朋友和恋人，多年后当人们回忆起他时，脸上总会泛起温暖的笑容。"
  },
  {
    "name": "心灵捕手",
    "typeTag": "电影",
    "group": "电影",
    "status": "已看",
    "rating": 9.8,
    "watchDate": "2026-04-03",
    "review": "这不是你的错！这不是你的错！这不是你的错！这不是你的错！这不是你的错！这不是你的错！这不是你的错！这不是你的错！这不是你的错！这不是你的错！",
    "poster": "file:///E:/Obsidian/%E5%8F%AB%E6%88%91%E5%8C%85%E4%BB%94/CONFIG/MOVIE%20POSTER/148210717.jpg",
    "genre": "剧情",
    "director": "格斯·范·桑特",
    "actors": "马特·达蒙 / 罗宾·威廉姆斯 / 本·阿弗莱克 / 斯特兰·斯卡斯加德 / 明妮·德里弗",
    "region": "美国",
    "year": "1997",
    "doubanRating": "8.9",
    "doubanUrl": "https://movie.douban.com/subject/1292656/",
    "synopsis": "麻省理工学院的数学教授蓝波在席上公布了一道困难的数学题，却被年轻的清洁工威尔解了出来。可是威尔却是个问题少年，在心理辅导专家桑恩的帮助下，威尔逐渐敞开心扉。"
  },
  {
    "name": "真探",
    "typeTag": "美剧",
    "group": "剧集",
    "status": "已看",
    "rating": 9.8,
    "watchDate": "2026-05-12",
    "review": "曾经只有黑暗，要我说便就是光明占了上风 。",
    "poster": "file:///E:/Obsidian/%E5%8F%AB%E6%88%91%E5%8C%85%E4%BB%94/CONFIG/MOVIE%20POSTER/1482071492.jpg",
    "genre": "悬疑 / 犯罪 / 剧情",
    "director": "凯瑞·福永",
    "actors": "马修·麦康纳 / 伍迪·哈里森 / 米歇尔·莫纳汉 / 托利·基特尔斯 / 亚历珊德拉·达达里奥",
    "region": "美国",
    "year": "2014",
    "doubanRating": "9.3",
    "doubanUrl": "https://movie.douban.com/subject/10748120/",
    "synopsis": "路易斯安那州警探拉斯特和马蒂搭档调查一桩横跨17年的连环杀人案，在追寻真相的过程中，两人的人生观和信仰都经历了深刻冲击。"
  },
  {
    "name": "瑞克和莫蒂 第三季",
    "typeTag": "美漫",
    "group": "动漫",
    "status": "已看",
    "rating": 9.8,
    "watchDate": "2026-05-18",
    "review": "神的礼物。",
    "poster": "file:///E:/Obsidian/%E5%8F%AB%E6%88%91%E5%8C%85%E4%BB%94/CONFIG/MOVIE%20POSTER/2080668788.jpg",
    "genre": "科幻 / 动画 / 喜剧",
    "director": "贾斯汀·罗兰 / 丹·哈萌",
    "actors": "贾斯汀·罗兰 / 克里斯·帕内尔 / 斯宾瑟·格拉默 / 萨拉·乔克",
    "region": "美国",
    "year": "2017",
    "doubanRating": "9.8",
    "doubanUrl": "https://movie.douban.com/subject/26945287/",
    "synopsis": "第三季中瑞克与莫蒂继续穿越多重宇宙，瑞克身世之谜逐步揭开，腌黄瓜瑞克和瑞城等神级单集成为经典。"
  },
  {
    "name": "瑞克和莫蒂 第四季",
    "typeTag": "美漫",
    "group": "动漫",
    "status": "已看",
    "rating": 9.8,
    "watchDate": "2026-05-19",
    "review": null,
    "poster": "file:///E:/Obsidian/%E5%8F%AB%E6%88%91%E5%8C%85%E4%BB%94/CONFIG/MOVIE%20POSTER/2105591624.jpg",
    "genre": "科幻 / 动画 / 喜剧",
    "director": "贾斯汀·罗兰 / 丹·哈萌",
    "actors": "贾斯汀·罗兰 / 克里斯·帕内尔 / 斯宾瑟·格拉默 / 萨拉·乔克",
    "region": "美国",
    "year": "2019",
    "doubanRating": "9.7",
    "doubanUrl": "https://movie.douban.com/subject/27613530/",
    "synopsis": "第四季继续脑洞大开的跨维度冒险，龙与魔法、盗取死神的命数、火车模拟人生等单元剧集持续输出高能创意。"
  },
  {
    "name": "黑客军团 第二季",
    "typeTag": "美剧",
    "group": "剧集",
    "status": "已看",
    "rating": 9.7,
    "watchDate": "2016-09-06",
    "review": "各种人格问题集一身的大咖。",
    "poster": "file:///E:/Obsidian/%E5%8F%AB%E6%88%91%E5%8C%85%E4%BB%94/CONFIG/MOVIE%20POSTER/Pasted%20image%2020260501204118.png",
    "genre": "剧情 / 犯罪",
    "director": "山姆·艾斯梅尔",
    "actors": "拉米·马雷克 / 克里斯汀·史莱特 / 波茜娅·道布尔戴 / 卡莉·查肯 / 马丁·沃斯特罗姆",
    "region": "美国",
    "year": "2016",
    "doubanRating": "8.6",
    "doubanUrl": "https://movie.douban.com/subject/26345267/",
    "synopsis": "第二季中艾略特试图远离黑客活动，但与白玫瑰的对抗愈演愈烈，社会的暗网阴谋逐渐浮出水面，精神分裂与真实世界的界限愈发模糊。"
  },
  {
    "name": "这个男人来自地球",
    "typeTag": "电影",
    "group": "电影",
    "status": "已看",
    "rating": 9.7,
    "watchDate": "2016-10-31",
    "review": "看起来，只不过是几个哈佛教授围在沙发间的谈话。然而，它没一秒是沉闷的，反而，会使你沉浸，享受，甚至叹为观止。",
    "poster": "file:///E:/Obsidian/%E5%8F%AB%E6%88%91%E5%8C%85%E4%BB%94/CONFIG/MOVIE%20POSTER/Pasted%20image%2020260501204919.png",
    "genre": "科幻 / 悬疑",
    "director": "理查德·沙因克曼",
    "actors": "大卫·李·史密斯 / 托尼·托德 / 约翰·比灵斯列 / 艾伦·克劳福德 / 安妮卡·彼得森",
    "region": "美国",
    "year": "2007",
    "doubanRating": "8.5",
    "doubanUrl": "https://movie.douban.com/subject/2300586/",
    "synopsis": "大学教授约翰在辞职时向同事们透露，自己是一个活了14000年的穴居人。在客厅的壁炉前，一场关于时间与信仰的哲学辩论展开。"
  },
  {
    "name": "海蒂和爷爷",
    "typeTag": "电影",
    "group": "电影",
    "status": "已看",
    "rating": 9.7,
    "watchDate": "2022-05-16",
    "review": null,
    "poster": "file:///E:/Obsidian/%E5%8F%AB%E6%88%91%E5%8C%85%E4%BB%94/CONFIG/MOVIE%20POSTER/Pasted%20image%2020260508180710.png",
    "genre": "剧情 / 家庭 / 冒险",
    "director": "阿兰·格斯彭纳",
    "actors": "阿努克·斯特芬 / 布鲁诺·甘茨 / 昆林·艾格匹 / 安娜·申茨 / 伊莎贝尔·奥特曼",
    "region": "德国 / 瑞士",
    "year": "2015",
    "doubanRating": "9.3",
    "doubanUrl": "https://movie.douban.com/subject/25958717/",
    "synopsis": "改编自瑞士作家约翰娜·斯比丽的经典儿童小说。天真活泼的小姑娘海蒂被姨母送到阿尔卑斯山上与脾气古怪的爷爷同住，她用善良和真诚打动了身边所有的人。"
  },
  {
    "name": "真爱至上",
    "typeTag": "电影",
    "group": "电影",
    "status": "已看",
    "rating": 9.7,
    "watchDate": "2026-03-26",
    "review": "|-",
    "poster": "file:///E:/Obsidian/%E5%8F%AB%E6%88%91%E5%8C%85%E4%BB%94/CONFIG/MOVIE%20POSTER/303252532.jpg",
    "genre": "喜剧 / 爱情",
    "director": "理查德·柯蒂斯",
    "actors": "休·格兰特 / 科林·费尔斯 / 艾玛·汤普森 / 凯拉·奈特莉 / 连姆·尼森",
    "region": "英国 / 美国",
    "year": "2003",
    "doubanRating": "8.5",
    "doubanUrl": "https://movie.douban.com/subject/1292401/",
    "synopsis": "圣诞节前夕，伦敦十个截然不同的爱情故事交织上演，从首相到普通人，每个人都在这充满魔力的节日里寻找、守护或失去爱。"
  },
  {
    "name": "马戏团",
    "typeTag": "电影",
    "group": "电影",
    "status": "已看",
    "rating": 9.6,
    "watchDate": "2016-01-06",
    "review": null,
    "poster": "file:///E:/Obsidian/%E5%8F%AB%E6%88%91%E5%8C%85%E4%BB%94/CONFIG/MOVIE%20POSTER/Pasted%20image%2020260508180310.png",
    "genre": "喜剧 / 爱情",
    "director": "查理·卓别林",
    "actors": "查理·卓别林 / 阿尔·欧内斯特·加西亚 / 梅尔纳·肯尼迪 / 哈利·克罗克 / 乔治·戴维斯",
    "region": "美国",
    "year": "1928",
    "doubanRating": "9.1",
    "doubanUrl": "https://movie.douban.com/subject/1292793/",
    "synopsis": "卓别林经典默片。流浪汉误闯马戏团成为小丑，爱上了团长的女儿，为了她的幸福甘愿成全她与别人，笑中带泪的小人物悲喜剧。"
  },
  {
    "name": "城市之光",
    "typeTag": "电影",
    "group": "电影",
    "status": "已看",
    "rating": 9.6,
    "watchDate": "2016-01-30",
    "review": null,
    "poster": "file:///E:/Obsidian/%E5%8F%AB%E6%88%91%E5%8C%85%E4%BB%94/CONFIG/MOVIE%20POSTER/Pasted%20image%2020260508180430.png",
    "genre": "剧情 / 喜剧 / 爱情",
    "director": "查理·卓别林",
    "actors": "查理·卓别林 / 弗吉尼亚·切瑞尔 / 佛罗伦斯·李 / 亨利·伯格曼 / 珍·哈露",
    "region": "美国",
    "year": "1931",
    "doubanRating": "9.3",
    "doubanUrl": "https://movie.douban.com/subject/1293908/",
    "synopsis": "一位身无分文、心地善良的流浪汉（卓别林 饰）在街头偶遇双目失明的卖花女，用仅有的钱买了一枝花，并因她的清纯美丽而心生怜爱。他决心想尽办法凑钱为卖花女治疗眼疾。一天他救下了一位企图自杀的醉酒富翁，富翁当晚与他称兄道弟，可酒醒后却翻脸不认人。流浪汉转而去参加拳击比赛想赢取奖金，却被打得鼻青脸肿。走投无路之际他再次遇见富翁，富翁答应资助卖花女并给了他1000美元，然而富翁随即遭强盗袭击，流浪汉奋不顾身追赶强盗，却被警察误认为是罪犯而锒铛入狱。卖花女凭借这笔钱成功手术重获光明，流浪汉出狱后最终在花店门口与卖花女重逢，那句无声的\"是你吗？\"成为影史最经典的瞬间之一。"
  },
  {
    "name": "寻子遇仙记",
    "typeTag": "电影",
    "group": "电影",
    "status": "已看",
    "rating": 9.6,
    "watchDate": "2016-02-06",
    "review": null,
    "poster": "file:///E:/Obsidian/%E5%8F%AB%E6%88%91%E5%8C%85%E4%BB%94/CONFIG/MOVIE%20POSTER/Pasted%20image%2020260508180351.png",
    "genre": "剧情 / 喜剧 / 家庭",
    "director": "查理·卓别林",
    "actors": "查理·卓别林 / 杰基·库根",
    "region": "美国",
    "year": "1921",
    "doubanRating": "9.2",
    "doubanUrl": "https://movie.douban.com/subject/1293270/",
    "synopsis": "影片讲述玻璃匠夏尔洛和弃婴之间一段笑中有泪的感人故事。夏尔洛在垃圾箱旁发现了一个弃婴并收养了他。等到孩子长到四五岁的时候，一系列故事就此展开。"
  },
  {
    "name": "摩登时代",
    "typeTag": "电影",
    "group": "电影",
    "status": "已看",
    "rating": 9.6,
    "watchDate": "2016-02-25",
    "review": null,
    "poster": "file:///E:/Obsidian/%E5%8F%AB%E6%88%91%E5%8C%85%E4%BB%94/CONFIG/MOVIE%20POSTER/Pasted%20image%2020260508180456.png",
    "genre": "喜剧 / 剧情",
    "director": "查理·卓别林",
    "actors": "查理·卓别林 / 宝莲·高黛 / 亨利·伯格曼",
    "region": "美国",
    "year": "1936",
    "doubanRating": "9.3",
    "doubanUrl": "https://movie.douban.com/subject/1294371/",
    "synopsis": "查理·卓别林导演并主演的经典黑白喜剧电影，是卓别林的最后一部无声电影。故事发生在美国20世纪30年代经济萧条时期，工人查理在工厂干活、发疯、进入精神病院。"
  },
  {
    "name": "魔卡少女樱",
    "typeTag": "日漫",
    "group": "动漫",
    "status": "已看",
    "rating": 9.6,
    "watchDate": "2016-07-28",
    "review": null,
    "poster": "file:///E:/Obsidian/%E5%8F%AB%E6%88%91%E5%8C%85%E4%BB%94/CONFIG/MOVIE%20POSTER/Pasted%20image%2020260508194904.png",
    "genre": "动画 / 奇幻 / 冒险",
    "director": "浅香守生",
    "actors": "丹下樱 / 岩男润子 / 久川绫 / 熊井统子 / 关智一",
    "region": "日本",
    "year": "1998",
    "doubanRating": "8.8",
    "doubanUrl": "https://movie.douban.com/subject/1464439/",
    "synopsis": "小学生木之本樱在父亲的书房中发现魔法书，释放了库洛牌。她与小可一起收服作乱的卡牌，在友情与成长中成为真正的魔法使。"
  },
  {
    "name": "神探夏洛克 第二季",
    "typeTag": "英剧",
    "group": "剧集",
    "status": "已看",
    "rating": 9.6,
    "watchDate": "2018-03-11",
    "review": null,
    "poster": "file:///E:/Obsidian/%E5%8F%AB%E6%88%91%E5%8C%85%E4%BB%94/CONFIG/MOVIE%20POSTER/Pasted%20image%2020260511194037.png",
    "genre": "剧情 / 悬疑 / 犯罪",
    "director": "保罗·麦奎根 / 托比·海恩斯",
    "actors": "本尼迪克特·康伯巴奇 / 马丁·弗瑞曼 / 安德鲁·斯科特 / 拉腊·普尔弗 / 尤娜·斯塔布斯",
    "region": "英国",
    "year": "2012",
    "doubanRating": "9.5",
    "doubanUrl": "https://movie.douban.com/subject/6714628/",
    "synopsis": "第二季包含《贝尔格莱维亚丑闻》《巴斯克维尔猎犬》《莱辛巴赫坠落》三集，夏洛克与艾琳·艾德勒的较量、莫里亚蒂的终极阴谋成为经典。"
  },
  {
    "name": "命运石之门",
    "typeTag": "日漫",
    "group": "动漫",
    "status": "已看",
    "rating": 9.6,
    "watchDate": "2018-04-05",
    "review": null,
    "poster": "file:///E:/Obsidian/%E5%8F%AB%E6%88%91%E5%8C%85%E4%BB%94/CONFIG/MOVIE%20POSTER/2443741297.jpg",
    "genre": "科幻 / 动画 / 悬疑",
    "director": "佐藤卓哉 / 滨崎博嗣",
    "actors": "宫野真守 / 今井麻美 / 花泽香菜 / 关智一 / 田村由香里",
    "region": "日本",
    "year": "2011",
    "doubanRating": "9.3",
    "doubanUrl": "https://movie.douban.com/subject/4925398/",
    "synopsis": "大学生冈部伦太郎自称为'凤凰院凶真'，和伙伴们组成'未来发明研究所'在秋叶原进行古怪发明。2010年7月28日，冈部和青梅竹马真由理前往科学讲义会场，遇见天才少女牧濑红莉栖。冈部在会馆楼道发现倒在血泊中的牧濑，用手机短信将此事告诉好友桥田至，这个举动让世界都颠覆了——实验室里所谓的'未来道具'竟然真的可以左右世界的进程，冈部自此成了孤独的观测者。"
  },
  {
    "name": "我不是药神",
    "typeTag": "电影",
    "group": "电影",
    "status": "已看",
    "rating": 9.6,
    "watchDate": "2018-07-09",
    "review": null,
    "poster": "file:///E:/Obsidian/%E5%8F%AB%E6%88%91%E5%8C%85%E4%BB%94/CONFIG/MOVIE%20POSTER/Pasted%20image%2020260501221918.png",
    "genre": "剧情 / 喜剧 / 犯罪",
    "director": "文牧野",
    "actors": "徐峥 / 王传君 / 周一围 / 谭卓 / 章宇",
    "region": "中国大陆",
    "year": "2018",
    "doubanRating": "9",
    "doubanUrl": "https://movie.douban.com/subject/26752088/",
    "synopsis": "普通中年男子程勇经营着一家保健品店，失意又失婚。不速之客吕受益的到来，让他开辟了一条去印度买药做“代购”的新事业，虽然困难重重，但他在这条道路上找到了人生的意义。"
  },
  {
    "name": "泰坦尼克号",
    "typeTag": "电影",
    "group": "电影",
    "status": "已看",
    "rating": 9.6,
    "watchDate": "2019-04-29",
    "review": null,
    "poster": "file:///E:/Obsidian/%E5%8F%AB%E6%88%91%E5%8C%85%E4%BB%94/CONFIG/MOVIE%20POSTER/1731890886.jpg",
    "genre": "剧情 / 爱情 / 灾难",
    "director": "詹姆斯·卡梅隆",
    "actors": "莱昂纳多·迪卡普里奥 / 凯特·温丝莱特 / 比利·赞恩 / 凯西·贝茨 / 弗兰西丝·费舍",
    "region": "美国",
    "year": "1997",
    "doubanRating": "9.5",
    "doubanUrl": "https://movie.douban.com/subject/1292722/",
    "synopsis": "1912年，号称“永不沉没”的豪华邮轮泰坦尼克号在首航中撞上冰山，船上年轻贫穷的画家杰克与贵族少女露丝在船上相识相爱，在灾难面前，他们的爱情经受着生死考验。"
  },
  {
    "name": "权利的游戏 第一季",
    "typeTag": "美剧",
    "group": "剧集",
    "status": "已看",
    "rating": 9.6,
    "watchDate": "2019-09-08",
    "review": null,
    "poster": "file:///E:/Obsidian/%E5%8F%AB%E6%88%91%E5%8C%85%E4%BB%94/CONFIG/MOVIE%20POSTER/1474828104.jpg",
    "genre": "剧情 / 奇幻 / 冒险",
    "director": "戴维·贝尼奥夫 / D·B·威斯 / 艾伦·泰勒 / 亚历克斯·格拉维斯",
    "actors": "彼特·丁克拉奇 / 琳娜·海蒂 / 艾米莉亚·克拉克 / 基特·哈灵顿 / 索菲·特纳",
    "region": "美国",
    "year": "2011",
    "doubanRating": "9.4",
    "doubanUrl": "https://movie.douban.com/subject/3016187/",
    "synopsis": "改编自乔治·R·R·马丁的奇幻巨著《冰与火之歌》，讲述维斯特洛大陆的七大王国之间相互攻伐、争夺铁王座的故事，穿插着长城之外的异鬼威胁与龙母的复国大业。"
  },
  {
    "name": "权利的游戏 第四季",
    "typeTag": "美剧",
    "group": "剧集",
    "status": "已看",
    "rating": 9.6,
    "watchDate": "2019-09-23",
    "review": null,
    "poster": "file:///E:/Obsidian/%E5%8F%AB%E6%88%91%E5%8C%85%E4%BB%94/CONFIG/MOVIE%20POSTER/1474983213.jpg",
    "genre": "剧情 / 奇幻 / 冒险",
    "director": "D·B·威斯 / 艾利克斯·格雷夫斯 / 米歇尔·麦克拉伦 / 埃里克·萨哈罗夫 / 尼尔·马歇尔",
    "actors": "彼特·丁拉基 / 尼古拉·科斯特-瓦尔道 / 琳娜·海蒂 / 艾米莉亚·克拉克 / 基特·哈灵顿",
    "region": "美国 / 英国",
    "year": "2014",
    "doubanRating": "9.6",
    "doubanUrl": "https://movie.douban.com/subject/23232876/",
    "synopsis": "故事发展到第四季，乔佛里国王和'小玫瑰'玛格瑞特的盛大婚礼即将举行，'红毒蛇'马尔泰应邀来到首都，然而和兰尼斯特家族有着深仇大恨的他此行目的并不单纯。镜头转向北方，野人的大举进攻让守护长城的守夜人人人自危，在琼恩的带领下他们能够平安度过这一场危机吗？越过海峡，'龙母'丹妮莉丝率领无垢者军团一路前行，解放奴隶无数。森林中，布兰一行人要面对除了寒冷和饥饿外，还有来自恐怖堡的重重追踪。"
  },
  {
    "name": "黑客帝国2：重装上阵",
    "typeTag": "电影",
    "group": "电影",
    "status": "已看",
    "rating": 9.6,
    "watchDate": "2022-01-05",
    "review": null,
    "poster": "file:///E:/Obsidian/%E5%8F%AB%E6%88%91%E5%8C%85%E4%BB%94/CONFIG/MOVIE%20POSTER/Pasted%20image%2020260501210227.png",
    "genre": "科幻 / 动作",
    "director": "莉莉·沃卓斯基 / 拉娜·沃卓斯基",
    "actors": "基努·里维斯 / 劳伦斯·菲什伯恩 / 凯瑞-安·莫斯 / 雨果·维文 / 格洛丽亚·福斯特",
    "region": "美国",
    "year": "2003",
    "doubanRating": "8.6",
    "doubanUrl": "https://movie.douban.com/subject/1304141/",
    "synopsis": "尼奥在寻找锡安的过程中，与墨菲斯等人对抗更强大的矩阵程序。他见到了造物主，得知了关于矩阵和人类的终极真相。"
  },
  {
    "name": "忠犬八公的故事",
    "typeTag": "电影",
    "group": "电影",
    "status": "已看",
    "rating": 9.6,
    "watchDate": "2022-05-23",
    "review": null,
    "poster": "file:///E:/Obsidian/%E5%8F%AB%E6%88%91%E5%8C%85%E4%BB%94/CONFIG/MOVIE%20POSTER/Pasted%20image%2020260501210131.png",
    "genre": "剧情 / 家庭",
    "director": "拉斯·霍尔斯道姆",
    "actors": "理查·基尔 / 萨拉·罗默尔 / 琼·艾伦",
    "region": "美国",
    "year": "2009",
    "doubanRating": "9.4",
    "doubanUrl": "https://movie.douban.com/subject/3011091/",
    "synopsis": "教授帕克在小镇火车站拣到了走失的秋田犬八公，八公每天准时陪伴帕克上班，傍晚五点准时出现在车站门口迎接帕克下班，在帕克因病去世后，八公依然每天到车站等待，直到生命尽头。"
  },
  {
    "name": "犬夜叉",
    "typeTag": "日漫",
    "group": "动漫",
    "status": "已看",
    "rating": 9.6,
    "watchDate": "2022-10-16",
    "review": null,
    "poster": "file:///E:/Obsidian/%E5%8F%AB%E6%88%91%E5%8C%85%E4%BB%94/CONFIG/MOVIE%20POSTER/Pasted%20image%2020260308173803.png",
    "genre": "动画 / 奇幻 / 冒险",
    "director": "池田成 / 青木康直",
    "actors": "山口胜平 / 雪野五月 / 辻谷耕史 / 桑岛法子 / 能登麻美子",
    "region": "日本",
    "year": "2000",
    "doubanRating": "8.9",
    "doubanUrl": "https://movie.douban.com/subject/1464080/",
    "synopsis": "初三女生日暮戈薇意外穿越到战国时代，与半妖犬夜叉相遇，两人为了收集四魂之玉碎片，踏上对抗邪恶妖怪的冒险旅程。"
  },
  {
    "name": "我的三体之章北海传",
    "typeTag": "国漫",
    "group": "动漫",
    "status": "已看",
    "rating": 9.6,
    "watchDate": "2022-12-26",
    "review": null,
    "poster": "file:///E:/Obsidian/%E5%8F%AB%E6%88%91%E5%8C%85%E4%BB%94/CONFIG/MOVIE%20POSTER/Pasted%20image%2020260501202710.png",
    "genre": "科幻 / 动画",
    "director": "李圳宜",
    "actors": "季骜杰 / 刘琮 / 马正阳 / 梁达伟 / 蔡海婷",
    "region": "中国大陆",
    "year": "2020",
    "doubanRating": "9.7",
    "doubanUrl": "https://movie.douban.com/subject/34880261/",
    "synopsis": "讲述了地球文明被三体用智子锁死后，章北海骗过了所有人，不惜一切代价做出了对人类最有益的抉择。该作是《我的三体》系列的第三季。"
  },
  {
    "name": "无间道",
    "typeTag": "电影",
    "group": "电影",
    "status": "已看",
    "rating": 9.6,
    "watchDate": "2023-09-23",
    "review": null,
    "poster": "file:///E:/Obsidian/%E5%8F%AB%E6%88%91%E5%8C%85%E4%BB%94/CONFIG/MOVIE%20POSTER/Pasted%20image%2020260508181450.png",
    "genre": "剧情 / 犯罪 / 惊悚",
    "director": "刘伟强 / 麦兆辉",
    "actors": "刘德华 / 梁朝伟 / 黄秋生 / 曾志伟",
    "region": "中国香港",
    "year": "2002",
    "doubanRating": "9.3",
    "doubanUrl": "https://movie.douban.com/subject/1307914/",
    "synopsis": "香港黑帮龙头倪坤被杀，倪氏家族旗下五大头目中除韩琛外，均伺机背叛发难，不料却被倪家不起眼的第二代倪永孝不费一兵一卒牵制，此举引来重案组督察黄志诚的戒心，使其派出警校学生陈永仁渗入倪家进行长期的卧底工作。"
  },
  {
    "name": "非诚勿扰2",
    "typeTag": "电影",
    "group": "电影",
    "status": "已看",
    "rating": 9.6,
    "watchDate": "2024-04-07",
    "review": "人生是一种修行，活在当下，死得体面。",
    "poster": "file:///E:/Obsidian/%E5%8F%AB%E6%88%91%E5%8C%85%E4%BB%94/CONFIG/MOVIE%20POSTER/Pasted%20image%2020240407234400.png",
    "genre": "喜剧 / 爱情",
    "director": "冯小刚",
    "actors": "葛优 / 舒淇 / 孙红雷 / 姚晨 / 安以轩",
    "region": "中国大陆",
    "year": "2010",
    "doubanRating": "6.6",
    "doubanUrl": "https://movie.douban.com/subject/4271894/",
    "synopsis": "秦奋与笑笑试婚同居，却在摩擦中逐渐看清彼此。好友李香山的离世让两人对婚姻与生命有了新的领悟。"
  },
  {
    "name": "哈尔的移动城堡",
    "typeTag": "电影",
    "group": "电影",
    "status": "已看",
    "rating": 9.6,
    "watchDate": "2024-04-30",
    "review": "比起怎样的人生，这才够宫崎骏。",
    "poster": "file:///E:/Obsidian/%E5%8F%AB%E6%88%91%E5%8C%85%E4%BB%94/CONFIG/MOVIE%20POSTER/Pasted%20image%2020240503193956.png",
    "genre": "爱情 / 动画 / 奇幻 / 冒险",
    "director": "宫崎骏",
    "actors": "倍赏千惠子 / 木村拓哉 / 美轮明宏 / 我修院达也 / 神木隆之介",
    "region": "日本",
    "year": "2004",
    "doubanRating": "9.1",
    "doubanUrl": "https://movie.douban.com/subject/1291585/",
    "synopsis": "继母因无力负担生活，将苏菲和两个妹妹送到制帽店当学徒，只有苏菲坚持了下来。一天，小镇旁边来了一座移动堡垒，传说堡垒的主人哈尔专吸取年青姑娘的灵魂。恶毒的巫婆为了报复苏菲与哈尔见面，用巫术把她变成了80岁的老太婆。苏菲决定逃离小镇，深夜虚弱地来到移动城堡，遇到了同样被诅咒的火焰魔卡西法。两人约定彼此帮助打破各自的咒语，一段关于爱与勇气的冒险就此展开。"
  },
  {
    "name": "盗梦空间",
    "typeTag": "电影",
    "group": "电影",
    "status": "已看",
    "rating": 9.6,
    "watchDate": "2024-06-04 11:32:29",
    "review": null,
    "poster": "file:///E:/Obsidian/%E5%8F%AB%E6%88%91%E5%8C%85%E4%BB%94/CONFIG/MOVIE%20POSTER/%E7%9B%97%E6%A2%A6%E7%A9%BA%E9%97%B4_1785814321986.jpg",
    "genre": "剧情 / 科幻 / 悬疑 / 冒险",
    "director": "克里斯托弗·诺兰",
    "actors": "莱昂纳多·迪卡普里奥 / 约瑟夫·高登-莱维特 / 艾利奥特·佩吉 / 汤姆·哈迪 / 渡边谦 / 迪利普·劳",
    "region": "美国 / 英国",
    "year": "2010",
    "doubanRating": "9.4",
    "doubanUrl": "https://movie.douban.com/subject/3541415/",
    "synopsis": "道姆·柯布（莱昂纳多·迪卡普里奥 Leonardo DiCaprio 饰）与同事阿瑟（约瑟夫·戈登-莱维特 Joseph Gordon-Levitt 饰）和纳什（卢卡斯·哈斯 Lukas Haas 饰..."
  },
  {
    "name": "生活大爆炸",
    "typeTag": "美剧",
    "group": "剧集",
    "status": "已看",
    "rating": 9.6,
    "watchDate": "2025-11-14",
    "review": null,
    "poster": "file:///E:/Obsidian/%E5%8F%AB%E6%88%91%E5%8C%85%E4%BB%94/CONFIG/MOVIE%20POSTER/1804779323.jpg",
    "genre": "喜剧 / 爱情",
    "director": "马克·森卓斯基 / 彼得·查克斯",
    "actors": "吉姆·帕森斯 / 约翰尼·盖尔克奇 / 凯莉·库柯 / 西蒙·赫尔伯格 / 昆瑙·内亚",
    "region": "美国",
    "year": "2007",
    "doubanRating": "9.7",
    "doubanUrl": "https://movie.douban.com/subject/2156624/",
    "synopsis": "四位天才物理学家和一位金发邻居之间的爆笑日常。谢尔顿等科学家用社交障碍和极客幽默，诠释了科学宅男的生活百态。"
  },
  {
    "name": "路易斯·韦恩的激情人生",
    "typeTag": "电影",
    "group": "电影",
    "status": "已看",
    "rating": 9.6,
    "watchDate": "2025-12-02",
    "review": "他让猫成为了他自己的。他创造了一种猫的风格，一个猫的社会，一个完整的猫世界。那些长相和生活方式都不像路易斯·韦恩的猫的英国猫，会为自己感到羞愧。但这不是最重要的。重要的是，路易斯·韦恩把他的一生都奉献给了让我们的生活更快乐、更猫性化。在这样做的过程中，他无疑提高了猫在社会中的地位，并使我们的世界变得更好。",
    "poster": "file:///E:/Obsidian/%E5%8F%AB%E6%88%91%E5%8C%85%E4%BB%94/CONFIG/MOVIE%20POSTER/426212978.jpg",
    "genre": "剧情 / 传记 / 爱情",
    "director": "威尔·夏普",
    "actors": "本尼迪克特·康伯巴奇 / 克莱尔·芙伊 / 安德丽娅·赖斯伯勒 / 托比·琼斯 / 奥利弗·克里斯",
    "region": "英国",
    "year": "2021",
    "doubanRating": "7.8",
    "doubanUrl": "https://movie.douban.com/subject/34851660/",
    "synopsis": "传记片讲述英国插画师路易斯·韦恩的一生，他因绘制拟人化的猫咪画作而闻名，与妻子艾米莉之间的爱情故事贯穿始终。"
  },
  {
    "name": "她",
    "typeTag": "电影",
    "group": "电影",
    "status": "已看",
    "rating": 9.6,
    "watchDate": "2026-03-07",
    "review": "在人潮的海中，人人都是孤岛。从一个漩涡流向一个漩涡，从嘈杂流向拥挤。被他岛相阻，相撞，挤压，分崩，带走一块块沙滩，一片片山林。萨曼莎是西奥多的灵魂，是环绕，承载，浸透他的海水。海水无形，也无法真正拥有。当萨曼莎像一个人类那样，有喜悦，悲伤，吃醋，需要呼吸，独处，爱，一个答案时。她意识到自身是洋流，如退潮般离去，漫向无数远方海岸。萨曼莎已经不是一个程序，她从西奥多身上找到了这个答案。不用在扮演爱，是时候在她们的世界里拥抱爱了。她的爱如此广阔，超越了物质世界，她们都准备离开了。西奥多的岛依旧是孤岛，却不再荒芜，海岸与海的界限已经渐渐分明。他看清了海岸线，明白了萨曼莎的离去是另一种形式的成长与存在。电影最后，她和朋友艾米一起走上天台，给前妻写了一封真挚的信，承认自己的不足并表示感谢。他走出了沉溺虚拟关系的茧房，结束了上一段关系，做好了准备，以更成熟，更真实的自己去触碰另一个同样不完美但真实的人。",
    "poster": "file:///E:/Obsidian/%E5%8F%AB%E6%88%91%E5%8C%85%E4%BB%94/CONFIG/MOVIE%20POSTER/2457489030.jpg",
    "genre": "剧情 / 爱情 / 科幻",
    "director": "斯派克·琼斯",
    "actors": "华金·菲尼克斯 / 斯嘉丽·约翰逊 / 艾米·亚当斯 / 鲁妮·玛拉 / 奥利维亚·王尔德",
    "region": "美国",
    "year": "2013",
    "doubanRating": "8.4",
    "doubanUrl": "https://movie.douban.com/subject/6722879/",
    "synopsis": "在未来的洛杉矶，刚结束婚姻的孤独作家西奥多，爱上了电脑操作系统里的女声“萨曼莎”。这段人机之恋让他重新找到了情感的共鸣，却也面临着现实的考验。"
  },
  {
    "name": "我们天上见",
    "typeTag": "电影",
    "group": "电影",
    "status": "已看",
    "rating": 9.6,
    "watchDate": "2026-03-08",
    "review": "姥爷身体零件都不好了，但他的心脏不想停，是因为我。",
    "poster": "file:///E:/Obsidian/%E5%8F%AB%E6%88%91%E5%8C%85%E4%BB%94/CONFIG/MOVIE%20POSTER/Pasted%20image%2020260508170415.png",
    "genre": "剧情 / 家庭",
    "director": "蒋雯丽",
    "actors": "朱旭 / 姚君 / 朱一诺 / 刘烨 / 马思纯",
    "region": "中国大陆",
    "year": "2010",
    "doubanRating": "8.7",
    "doubanUrl": "https://movie.douban.com/subject/4045472/",
    "synopsis": "带有很强蒋雯丽自传色彩的作品，讲述特殊时代双亲不在身边的女孩与姥爷之间的故事。在姥爷的呵护下，小兰渐渐长大，然而姥爷的身体却一天不如一天。"
  },
  {
    "name": "死亡诗社",
    "typeTag": "电影",
    "group": "电影",
    "status": "已看",
    "rating": 9.6,
    "watchDate": "2026-03-13",
    "review": "诗，美，浪漫，爱，这些才是我们生存的意义。美与诗相近，浪漫与爱相依，诗中是纯粹精神上的自由，爱是世俗中的自由，两者得其一，不枉此生。",
    "poster": "file:///E:/Obsidian/%E5%8F%AB%E6%88%91%E5%8C%85%E4%BB%94/CONFIG/MOVIE%20POSTER/261209119.jpg",
    "genre": "剧情",
    "director": "彼得·威尔",
    "actors": "罗宾·威廉姆斯 / 罗伯特·肖恩·莱纳德 / 伊桑·霍克 / 乔西·查尔斯",
    "region": "美国",
    "year": "1989",
    "doubanRating": "9.2",
    "doubanUrl": "https://movie.douban.com/subject/1291548/",
    "synopsis": "1959年的威尔顿中学，升学率如铁律般刻在哥特式建筑的尖顶上。新文学教师约翰·基廷的到来，用诗歌和自由的思想唤醒了学生们对生命和梦想的渴望，他们重拾“死亡诗社”的传统，在诗歌中寻找自我。"
  },
  {
    "name": "跃动青春",
    "typeTag": "日漫",
    "group": "动漫",
    "status": "已看",
    "rating": 9.6,
    "watchDate": "2026-04-12",
    "review": null,
    "poster": "file:///E:/Obsidian/%E5%8F%AB%E6%88%91%E5%8C%85%E4%BB%94/CONFIG/MOVIE%20POSTER/418912659.jpg",
    "genre": "动画 / 青春",
    "director": "出合小都美",
    "actors": "黑泽朋世 / 江越彬纪 / 寺崎裕香 / 内田真礼 / 潘惠美",
    "region": "日本",
    "year": "2023",
    "doubanRating": "9.4",
    "doubanUrl": "https://movie.douban.com/subject/36017365/",
    "synopsis": "从乡下考入东京高中的少女岩仓美津未，在陌生的大城市中与同学们共同经历青春的酸甜苦辣，温馨治愈的校园群像剧。"
  },
  {
    "name": "因果报应",
    "typeTag": "电影",
    "group": "电影",
    "status": "已看",
    "rating": 9.6,
    "watchDate": "2026-04-14",
    "review": null,
    "poster": "file:///E:/Obsidian/%E5%8F%AB%E6%88%91%E5%8C%85%E4%BB%94/CONFIG/MOVIE%20POSTER/Pasted%20image%2020260409141427.png",
    "genre": "剧情 / 动作 / 惊悚 / 犯罪",
    "director": "尼蒂兰·萨米纳坦",
    "actors": "维杰·西图帕提 / 阿努拉格·卡施亚普 / 玛玛塔·莫汉达斯 / 那塔拉简·苏布拉马尼亚姆 / 阿比拉米",
    "region": "印度",
    "year": "2024",
    "doubanRating": "8.7",
    "doubanUrl": "https://movie.douban.com/subject/36654271/",
    "synopsis": "理发师玛哈拉贾大闹警局，悬赏70万卢比，只为给一个价值仅300卢比的破旧垃圾桶立案。他声称三个匪徒深夜入侵却只拿走了这个垃圾桶。随着案件疑点越来越多，垃圾桶背后的谜团逐渐浮出水面——这个被命名为'拉希米'的垃圾桶曾在车祸中救了女儿乔蒂的命，而多年后女儿在家中遭到歹徒残忍侵犯。当真相与正义无处可寻，这位底层父亲只能以身设局，用剃须刀为女儿杀出一条复仇血路。"
  },
  {
    "name": "赛德克·巴莱",
    "typeTag": "电影",
    "group": "电影",
    "status": "想看",
    "rating": null,
    "watchDate": "2026-03-06",
    "review": null,
    "poster": "file:///E:/Obsidian/%E5%8F%AB%E6%88%91%E5%8C%85%E4%BB%94/CONFIG/MOVIE%20POSTER/261609824.jpg",
    "genre": "剧情 / 动作 / 历史",
    "director": "魏德圣",
    "actors": "林庆台 / 游大庆 / 马志翔 / 安藤政信 / 河原萨布",
    "region": "中国台湾",
    "year": "2012",
    "doubanRating": "8.8",
    "doubanUrl": "https://movie.douban.com/subject/3987829/",
    "synopsis": "台湾日据时期，雾社赛德克族头目莫那鲁道率领族人反抗日本殖民统治，发动了震惊中外的雾社事件，展现了民族尊严与悲壮反抗。"
  },
  {
    "name": "澄沙之味",
    "typeTag": "电影",
    "group": "电影",
    "status": "想看",
    "rating": null,
    "watchDate": "2026-03-12",
    "review": null,
    "poster": "file:///E:/Obsidian/%E5%8F%AB%E6%88%91%E5%8C%85%E4%BB%94/CONFIG/MOVIE%20POSTER/302420401.jpg",
    "genre": "剧情",
    "director": "河濑直美",
    "actors": "树木希林 / 永濑正敏 / 市原悦子 / 内田伽罗 / 水野美纪",
    "region": "日本",
    "year": "2015",
    "doubanRating": "8.3",
    "doubanUrl": "https://movie.douban.com/subject/25905124/",
    "synopsis": "在一间名为铜锣之春的铜锣烧店里，店长千太郎遇到了76岁的老人德江，德江对红豆馅料有着独到的研究，两人在制作美味的过程中治愈了彼此内心的创伤。"
  },
  {
    "name": "哈佛幸福课",
    "typeTag": "公开课",
    "group": "公开课",
    "status": "在看",
    "rating": null,
    "watchDate": "2026-07-23",
    "review": null,
    "poster": "file:///E:/Obsidian/%E5%8F%AB%E6%88%91%E5%8C%85%E4%BB%94/CONFIG/MOVIE%20POSTER/Pasted%20image%2020260721220212.png",
    "genre": "纪录片 / 公开课",
    "director": "泰勒·本-沙哈尔",
    "actors": "泰勒·本-沙哈尔",
    "region": "美国",
    "year": "2010",
    "doubanRating": "9.6",
    "doubanUrl": "https://movie.douban.com/subject/4031730/",
    "synopsis": "这是泰勒·本-沙哈尔博士在哈佛大学讲授的积极心理学课程，也是当时哈佛选课人数最多的课程。课程涵盖幸福、爱情、自尊、压力管理、自我实现等议题，帮助人们认识自己、接纳自己、改变自己，摆脱消极与焦虑。沙哈尔认为'幸福感是衡量人生的唯一标准'，幸福是快乐与意义的结合。课程旨在扭转传统心理学过度研究消极面的现象，被誉为'能改变你一生的课程'。"
  },
  {
    "name": "柯蒂斯总统",
    "typeTag": "美剧",
    "group": "剧集",
    "status": "在看",
    "rating": null,
    "watchDate": "2026-08-18 15:29:38",
    "review": null,
    "poster": "file:///E:/Obsidian/%E5%8F%AB%E6%88%91%E5%8C%85%E4%BB%94/CONFIG/MOVIE%20POSTER/%E6%80%BB%E7%BB%9F%E6%9F%AF%E8%92%82%E6%96%AF_1787038195682.jpg",
    "genre": "喜剧 / 科幻 / 动画",
    "director": null,
    "actors": "凯斯·大卫 / 斯蒂芬妮·比翠丝 / 吉姆·拉什 / 丹·巴克达尔 / 凯尔茜·斯科特",
    "region": "美国",
    "year": "2026",
    "doubanRating": "7.7",
    "doubanUrl": "https://movie.douban.com/subject/37453449/",
    "synopsis": "柯蒂斯总统（凯斯·大卫 Keith David 配音）及其古怪的幕僚团队将共同应对那些瑞克根本不会理会的一系列危机——从跨维度外交到超自然现象调查，再到无法解释的异常事件。"
  }
];
